### ISSUE TITLE
this.maps[key].setCenterAnimated is not a function

### ISSUE THREAD

**Issue by matte0080** [ihor-zinchenko/ngx-apple-maps#34]
Hi mate, thank you for your mapkitjs adapter.

I find a issue when define a map `settings` with `padding` property. When i go out from page where there is the map and then return on it. I received this exception and maps broken:

```
ERROR TypeError: this.maps[key].setCenterAnimated is not a function
    at /Users/Matte/Development/crossbar/node_modules/ngx-apple-maps/__ivy_ngcc__/fesm2015/ngx-apple-maps.js:611:1
    at DefaultKeyValueDiffer.forEachItem (/Users/Matte/Development/crossbar/node_modules/@angular/core/fesm2015/core.mjs:28221:1)
    at AppleMapsService.settingsChanged (/Users/Matte/Development/crossbar/node_modules/ngx-apple-maps/__ivy_ngcc__/fesm2015/ngx-apple-maps.js:600:1)
    at AppleMapsComponent.settingsChanged (/Users/Matte/Development/crossbar/node_modules/ngx-apple-maps/__ivy_ngcc__/fesm2015/ngx-apple-maps.js:923:1)
    at AppleMapsComponent.ngDoCheck (/Users/Matte/Development/crossbar/node_modules/ngx-apple-maps/__ivy_ngcc__/fesm2015/ngx-apple-maps.js:964:1)
    at callHook (/Users/Matte/Development/crossbar/node_modules/@angular/core/fesm2015/core.mjs:2561:1)
    at callHooks (/Users/Matte/Development/crossbar/node_modules/@angular/core/fesm2015/core.mjs:2520:1)
    at executeInitAndCheckHooks (/Users/Matte/Development/crossbar/node_modules/@angular/core/fesm2015/core.mjs:2471:1)
    at selectIndexInternal (/Users/Matte/Development/crossbar/node_modules/@angular/core/fesm2015/core.mjs:8416:1)
    at Module.ɵɵadvance (http://localhost:4200/vendor.js:56814:5) {stack: 'TypeError: this.maps[key].setCenterAnimated i…nce (http://localhost:4200/vendor.js:56814:5)', message: 'this.maps[key].setCenterAnimated is not a function'}
```

Then, why the maps array insiede `AppleMapsService` increse every time i go in out from map's page? When i go out the map is not destroyed?

**Comment by ihor-zinchenko** [comment]
Fixed in v1.0.0. Older versions are no longer supported. It will be released soon.
